build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
labels:
  io.hass.version: "1.0.0"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64|armhf|armv7|i386"