name: "CannaLog"
description: "A modern web application for managing plants, environments, measurements, actions and images"
version: "1.0.42"
slug: "cannalog"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
panel_icon: mdi:cannabis
panel_title: CannaLog
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: false
ingress: true
ingress_port: 5000
ports:
  5000/tcp: null
ports_description:
  5000/tcp: "CannaLog Web Interface"
map:
  - share:rw
  - ssl:rw
  - config:rw
options:
  secret_key: "change-this-secret-key-in-production"
  debug: false
  max_upload_mb: 20
schema:
  secret_key: str
  debug: bool
  max_upload_mb: int
#image: "ghcr.io/ninharp/addon-cannalog"